-- Criar regras semânticas, que são regras que não podem ser garantidas pela estrutura
-- do modelo relacional, usando o esquema exemplo fornecido. As regras criadas também
-- devem ser descritas textualmente no trabalho a ser entregue.